// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MonsterCatchAttempt, MonsterCatchAttemptTableId } from "./tables/MonsterCatchAttempt.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { Monster, MonsterTableId } from "./tables/Monster.sol";
import { Obstruction, ObstructionTableId } from "./tables/Obstruction.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Movable, MovableTableId } from "./tables/Movable.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { EncounterTrigger, EncounterTriggerTableId } from "./tables/EncounterTrigger.sol";
import { Encounterable, EncounterableTableId } from "./tables/Encounterable.sol";
import { Encounter, EncounterData, EncounterTableId } from "./tables/Encounter.sol";
