// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum TerrianType {
  None,
  TallGrass,
  Boulder
}

enum MonsterType {
  None,
  Eagle,
  Rat,
  Caterpillar
}

enum MonsterCatchResult {
  Missed,
  Caught,
  Fled
}
